➡ Fácil

1- Importe numpy como ‘np’ e imprima o número da versão.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.3'

2- Crie uma matriz 1D com números de 0 a 9

In [3]:
arr_1d = np.arange(0,10)

In [4]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [11]:
arr = np.ones((3, 3))

In [12]:
arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
arr.shape

(3, 3)

In [15]:
arr == 1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [18]:
arr_bool = np.array([[True,True,True],[True,True,True],[True,True,True]])

In [19]:
arr_bool

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

4- Extraia todos os números ímpares de ‘arr’

In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr_impar = (arr[arr%2 != 0 ])

In [23]:
arr_impar

array([1, 3, 5, 7, 9])

5- Substitua todos os números ímpares arr por -1

In [35]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.place(arr, arr % 2 != 0, -1)

In [41]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

➡ Médio

1- Substitua todos os números ímpares em arr com -1 sem alterar arr

In [53]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
array = np.copy(arr)

In [55]:
np.place(array, array % 2 != 0, -1)

In [56]:
array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

3- Empilhe matrizes verticalmente:

In [70]:
a = np.arange(10).reshape(2,-1)

In [71]:
b = np.repeat(1, 10).reshape(2,-1)

In [72]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [80]:
np.concatenate((a,b), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

4- Empilhe as matrizes horizontalmente:

In [81]:
np.concatenate((a,b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.

a = np.array([1,2,3])
Saída desejada: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [87]:
a = np.array([1,2,3])

In [88]:
a

array([1, 2, 3])

In [89]:
x = np.repeat(a,3)

In [90]:
x

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [91]:
y = np.tile(a,3)

In [92]:
y

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [94]:
np.concatenate((x,y),axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

➡ Difícil

1- Calcule a pontuação softmax de ‘sepal length’:

In [17]:
import numpy as np
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
data = np.genfromtxt(url, delimiter=",", dtype="float", usecols=[0,1,2,3])
data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

ttribute Information:
   1. sepal length in cm
   2. sepal width in cm
   3. petal length in cm
   4. petal width in cm
   5. class: 
      -- Iris Setosa
      -- Iris Versicolour
      -- Iris Virginica

In [32]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))


[ 0.00221959  0.00181724  0.00148783  0.00134625  0.00200836  0.00299613
  0.00134625  0.00200836  0.00110221  0.00181724  0.00299613  0.00164431
  0.00164431  0.00099732  0.0044697   0.00404435  0.00299613  0.00221959
  0.00404435  0.00221959  0.00299613  0.00221959  0.00134625  0.00221959
  0.00164431  0.00200836  0.00200836  0.00245302  0.00245302  0.00148783
  0.00164431  0.00299613  0.00245302  0.00331123  0.00181724  0.00200836
  0.00331123  0.00181724  0.00110221  0.00221959  0.00200836  0.00121813
  0.00110221  0.00200836  0.00221959  0.00164431  0.00221959  0.00134625
  0.00271101  0.00200836  0.01483991  0.00814432  0.01342771  0.00331123
  0.00900086  0.00404435  0.00736928  0.00181724  0.00994749  0.00245302
  0.00200836  0.00493978  0.0054593   0.00603346  0.00365948  0.01099368
  0.00365948  0.0044697   0.006668    0.00365948  0.00493978  0.00603346
  0.00736928  0.00603346  0.00814432  0.00994749  0.01214989  0.01099368
  0.0054593   0.00404435  0.00331123  0.00331123  0

In [15]:
def softmax(sepallength):
    e_sepallength = np.exp(sepallength - np.max(sepallength))
    print (sepallength)
    return e_sepallength / e_sepallength.sum()

2- Filtre as linhas de iris_2d que possuem petallength (coluna 3) > 1.5 e sepallength (coluna 1) < 5.0

In [24]:
sepal_length = data[:,0]
sepal_width = data[:,1]
petal_length = data[:,2]
petal_width = data[:,3]

In [28]:
data [(data[:,2]>1.5) & (data[:,0]<5)]

array([[ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 4.9,  2.4,  3.3,  1. ],
       [ 4.9,  2.5,  4.5,  1.7]])

3- Selecione as linhas de iris_2d que não têm nenhum valor ‘nan’

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [34]:
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [35]:
iris_2d

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  nan,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  nan,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

➡ Muito difícil

1- Calcule as contagens de valores únicos na linha.

In [2]:
import numpy as np

In [3]:
np.random.seed(100)

In [4]:
arr = np.random.randint(1,11,size=(6, 10))

In [5]:
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

2- Encontre todos os picos em uma matriz 1D numpy

In [28]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations


array([2, 5])

3- Calcule as codificações únicas (variáveis ​​binárias dummy para cada valor único na matriz)

In [29]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

In [30]:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

In [31]:
one_hot_encodings(arr)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])